# Generated by Django 4.0.5 on 2022-06-23 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(max_length=150)),
                ('scientific_name', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(max_length=2000)),
                ('category', models.CharField(choices=[('FRUIT', 'Fruit'), ('VEGETABLE', 'Vegetable'), ('Cash Crop', 'Cash Crop')], max_length=10)),
                ('tempmin', models.FloatField()),
                ('tempmax', models.FloatField()),
                ('rainmax', models.FloatField(blank=True, null=True)),
                ('rainmin', models.FloatField(blank=True, null=True)),
                ('phmax', models.FloatField()),
                ('phmin', models.FloatField()),
                ('organicmax', models.FloatField(blank=True, null=True)),
                ('organicmin', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('altitudemax', models.FloatField()),
                ('altitudemin', models.FloatField()),
                ('season', models.CharField(choices=[('WINTER', 'Winter'), ('SUMMER', 'Summer'), ('AUTUMN', 'Autumn'), ('SPRING', 'Spring')], max_length=7)),
                ('harvest', models.FloatField()),
                ('is_terrace', models.CharField(choices=[('YEs', 'Yes'), ('NO', 'No')], max_length=3)),
                ('link', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='UserCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('remarks', models.CharField(choices=[('FRUITFUL', 'Fruitful'), ('GOOD', 'Good'), ('NOTGOOD', 'Not So Good'), ('FRUITLESS', 'Fruitless')], max_length=10)),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
                ('temp', models.FloatField()),
                ('rain', models.FloatField(blank=True, null=True)),
                ('ph', models.FloatField()),
                ('organic', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField()),
                ('crop', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.crop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
