# Generated by Django 4.0.5 on 2022-06-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(max_length=150)),
                ('scientific_name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usercrop',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='usercrop',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='usercrop',
            name='longtitude',
        ),
        migrations.RemoveField(
            model_name='usercrop',
            name='organic',
        ),
        migrations.RemoveField(
            model_name='usercrop',
            name='ph',
        ),
        migrations.RemoveField(
            model_name='usercrop',
            name='rain',
        ),
        migrations.RemoveField(
            model_name='usercrop',
            name='temp',
        ),
    ]
