# Generated by Django 4.0.5 on 2022-06-24 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_requestcrop_remove_usercrop_altitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercrop',
            name='remarks',
        ),
    ]
