export const cropsData = [{
  "id": 1,
  "local_name": "Paddy",
  "scientific_name": "Oryza sativa",
  "description": "Paddy is a small, level, flooded field used to cultivate rice in southern and eastern Asia. Wet-rice cultivation is the most prevalent method of farming in the Far East, where it utilizes a small fraction of the total land yet feeds the majority of the rural population",
  "category": "Cash Crop",
  "tempmin": 15.0,
  "tempmax": 27.0,
  "rainmin": 100.0,
  "rainmax": 150.0,
  "phmin": 5.0,
  "phmax": 8.0,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 100.0,
  "altitudemax": 3050.0,
  "image": null,
  "season": "SPRING",
  "harvest": 5.0,
  "is_terrace": "NO",
  "link": "https://en.wikipedia.org/wiki/Rice"
},
{
  "id": 2,
  "local_name": "Barley",
  "scientific_name": "Hordeum Vulgare",
  "description": "Barley is a cereal grain with a chewy texture and mild, nutty flavor. It's the seed of a type of grass that grows in temperate climates throughout the world and one of the first grains to have been farmed by ancient civilizations.",
  "category": "Cash Crop",
  "tempmin": 12.0,
  "tempmax": 30.0,
  "rainmin": 39.0,
  "rainmax": 43.0,
  "phmin": 5.0,
  "phmax": 8.3,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 2500.0,
  "altitudemax": 4500.0,
  "image": null,
  "season": "SUMMER",
  "harvest": 6.0,
  "is_terrace": "NO",
  "link": "https://en.wikipedia.org/wiki/Barley"
},
{
  "id": 3,
  "local_name": "Maize",
  "scientific_name": "Zea mays",
  "description": "Maize is the world's leading crop and is widely cultivated as cereal grain. It is one of the most versatile emerging crops having wider adaptability. Globally, maize is known as queen of cereals because of its highest genetic yield potential.",
  "category": "Cash Crop",
  "tempmin": 15.0,
  "tempmax": 27.0,
  "rainmin": 65.0,
  "rainmax": 125.0,
  "phmin": 6.0,
  "phmax": 7.2,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 100.0,
  "altitudemax": 3200.0,
  "image": null,
  "season": "SUMMER",
  "harvest": 4.0,
  "is_terrace": "YEs",
  "link": "https://en.wikipedia.org/wiki/Maize"
},
{
  "id": 4,
  "local_name": "Wheat",
  "scientific_name": "Triticum",
  "description": "Wheat is a grass widely cultivated for its seed, a cereal grain which is a worldwide staple food. The many species of wheat together make up the genus Triticum; the most widely grown is common wheat (T. aestivum).",
  "category": "Cash Crop",
  "tempmin": 12.0,
  "tempmax": 25.0,
  "rainmin": 25.0,
  "rainmax": 75.0,
  "phmin": 6.0,
  "phmax": 7.0,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 100.0,
  "altitudemax": 4000.0,
  "image": null,
  "season": "SUMMER",
  "harvest": 5.0,
  "is_terrace": "NO",
  "link": "https://en.wikipedia.org/wiki/Wheat"
},
{
  "id": 5,
  "local_name": "Cotton",
  "scientific_name": "Gossypium",
  "description": "Cotton is a soft, fluffy staple fiber that grows in a boll, or protective case, around the seeds of the cotton plants of the genus Gossypium in the mallow family Malvaceae.",
  "category": "Cash Crop",
  "tempmin": 18.0,
  "tempmax": 27.0,
  "rainmin": 60.0,
  "rainmax": 110.0,
  "phmin": 6.0,
  "phmax": 6.5,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 100.0,
  "altitudemax": 1000.0,
  "image": null,
  "season": "SPRING",
  "harvest": 7.0,
  "is_terrace": "NO",
  "link": "https://en.wikipedia.org/wiki/Cotton"
},
{
  "id": 6,
  "local_name": "Sunflower",
  "scientific_name": "Helianthus",
  "description": "Sunflower is the common name for any of the plants of the genus Helianthus of the flowering plant family Asteraceae (known as the aster, daisy, or sunflower family).",
  "category": "Cash Crop",
  "tempmin": 21.0,
  "tempmax": 26.0,
  "rainmin": 20.0,
  "rainmax": 50.0,
  "phmin": 6.5,
  "phmax": 8.0,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 100.0,
  "altitudemax": 1000.0,
  "image": null,
  "season": "SPRING",
  "harvest": 4.0,
  "is_terrace": "NO",
  "link": "https://en.wikipedia.org/wiki/Common_sunflower"
},
{
  "id": 7,
  "local_name": "Beans",
  "scientific_name": "Phaseolus vulgaris",
  "description": "A bean is the seed of one of several genera of the flowering plant family Fabaceae, which are used as vegetables for human or animal food. They can be cooked in many different ways, including boiling, frying, and baking.",
  "category": "VEGETABLE",
  "tempmin": 10.0,
  "tempmax": 22.0,
  "rainmin": null,
  "rainmax": null,
  "phmin": 6.0,
  "phmax": 7.0,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 300.0,
  "altitudemax": 2500.0,
  "image": null,
  "season": "SPRING",
  "harvest": 2.0,
  "is_terrace": "YEs",
  "link": "https://en.wikipedia.org/wiki/Bean"
},
{
  "id": 8,
  "local_name": "Sugarcane",
  "scientific_name": "Saccharum Officinarum",
  "description": "Sugarcane or sugar cane is a species of (often hybrid) tall, perennial grass  that is used for sugar production. The plants are 2–6 m (6–20 ft) tall with stout, jointed, fibrous stalks that are rich in sucrose.",
  "category": "Cash Crop",
  "tempmin": 20.0,
  "tempmax": 25.0,
  "rainmin": 85.0,
  "rainmax": 165.0,
  "phmin": 6.5,
  "phmax": 7.5,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 100.0,
  "altitudemax": 1000.0,
  "image": null,
  "season": "AUTUMN",
  "harvest": 10.0,
  "is_terrace": "NO",
  "link": "https://en.wikipedia.org/wiki/Sugarcane"
},
{
  "id": 9,
  "local_name": "Okra",
  "scientific_name": "Abelmoschus esculentus",
  "description": "Okra known in many English-speaking countries as ladies' fingers or ochro, is a flowering plant in the mallow family. It has edible green seed pods. The plant is cultivated in tropical, subtropical, and warm temperate regions around the world.",
  "category": "VEGETABLE",
  "tempmin": 24.0,
  "tempmax": 27.0,
  "rainmin": null,
  "rainmax": null,
  "phmin": 6.0,
  "phmax": 6.8,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 230.0,
  "altitudemax": 1500.0,
  "image": null,
  "season": "SPRING",
  "harvest": 2.0,
  "is_terrace": "YEs",
  "link": "https://en.wikipedia.org/wiki/Okra"
},
{
  "id": 10,
  "local_name": "Tomato",
  "scientific_name": "Solanum Lycopersicum",
  "description": "The tomato is the edible berry of the plant Solanum lycopersicum, commonly known as the tomato plant. The species originated in western South America, Mexico, and Central America.",
  "category": "VEGETABLE",
  "tempmin": 10.0,
  "tempmax": 22.0,
  "rainmin": null,
  "rainmax": null,
  "phmin": 5.5,
  "phmax": 7.5,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 100.0,
  "altitudemax": 2000.0,
  "image": null,
  "season": "SPRING",
  "harvest": 3.0,
  "is_terrace": "YEs",
  "link": "https://en.wikipedia.org/wiki/Tomato"
},
{
  "id": 11,
  "local_name": "Grapes",
  "scientific_name": "Vitis Vinifera",
  "description": "A grape is a fruit, botanically a berry, of the deciduous woody vines of the flowering plant genus Vitis. Grapes can be eaten fresh as table grapes, used for making wine, jam, grape juice, jelly, grape seed extract, vinegar, and grape seed oil.",
  "category": "FRUIT",
  "tempmin": 25.0,
  "tempmax": 32.0,
  "rainmin": null,
  "rainmax": null,
  "phmin": 5.5,
  "phmax": 8.5,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 100.0,
  "altitudemax": 500.0,
  "image": null,
  "season": "WINTER",
  "harvest": 36.0,
  "is_terrace": "YEs",
  "link": "https://en.wikipedia.org/wiki/Grape"
},
{
  "id": 12,
  "local_name": "Strawberry",
  "scientific_name": "Fragaria X ananassa",
  "description": "Strawberries are bright red, juicy, and sweet. They're an excellent source of vitamin C and manganese and also contain decent amounts of folate (vitamin B9) and potassium.",
  "category": "FRUIT",
  "tempmin": 10.0,
  "tempmax": 27.0,
  "rainmin": null,
  "rainmax": null,
  "phmin": 5.0,
  "phmax": 7.5,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 1000.0,
  "altitudemax": 1500.0,
  "image": null,
  "season": "WINTER",
  "harvest": 6.0,
  "is_terrace": "YEs",
  "link": "https://en.wikipedia.org/wiki/Strawberry"
},
{
  "id": 13,
  "local_name": "Carrot",
  "scientific_name": "Daucus Carota",
  "description": "The carrot is a root vegetable, typically orange in color. The plant probably originated in Persia and was originally cultivated for its leaves and seeds. The most commonly eaten part of the plant is the taproot, although the stems and leaves are also eaten.",
  "category": "VEGETABLE",
  "tempmin": 16.0,
  "tempmax": 20.0,
  "rainmin": null,
  "rainmax": null,
  "phmin": 5.5,
  "phmax": 7.5,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 1000.0,
  "altitudemax": 1500.0,
  "image": "/images/images/carrot.jpg",
  "season": "AUTUMN",
  "harvest": 3.0,
  "is_terrace": "YEs",
  "link": "https://en.wikipedia.org/wiki/Carrot"
},
{
  "id": 14,
  "local_name": "Tobacco",
  "scientific_name": "Nicotiana Tabacum",
  "description": "Tobacco is the common name of several plants in the genus Nicotiana of the family Solanaceae, and the general term for any product prepared from the cured leaves of these plants.",
  "category": "Cash Crop",
  "tempmin": 24.0,
  "tempmax": 30.0,
  "rainmin": null,
  "rainmax": null,
  "phmin": 5.8,
  "phmax": 6.2,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 100.0,
  "altitudemax": 1000.0,
  "image": null,
  "season": "AUTUMN",
  "harvest": 4.0,
  "is_terrace": "NO",
  "link": "https://en.wikipedia.org/wiki/Tobacco"
},
{
  "id": 15,
  "local_name": "Cauliflower",
  "scientific_name": "Brassica Oleracea var.botrytis",
  "description": "Cauliflower is one of several vegetables in the species Brassica oleracea in the genus Brassica, which is in the Brassicaceae (or mustard) family. It is an annual plant that reproduces by seed. Cauliflower heads resemble those in broccoli, which differs in having flower buds as the edible portion.",
  "category": "VEGETABLE",
  "tempmin": 10.0,
  "tempmax": 25.0,
  "rainmin": null,
  "rainmax": null,
  "phmin": 5.5,
  "phmax": 7.5,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 100.0,
  "altitudemax": 3000.0,
  "image": null,
  "season": "AUTUMN",
  "harvest": 3.0,
  "is_terrace": "YEs",
  "link": "https://en.wikipedia.org/wiki/Cauliflower"
},
{
  "id": 16,
  "local_name": "Cucumber",
  "scientific_name": "Cucumis sativus",
  "description": "The cucumber is a member of the Cucurbitaceae family. Other members of the family include squash and different kinds of melon, including bitter melon. Cucumbers provide various nutrients but are low in calories, fat, cholesterol, and sodium.",
  "category": "VEGETABLE",
  "tempmin": 24.0,
  "tempmax": 30.0,
  "rainmin": null,
  "rainmax": null,
  "phmin": 5.5,
  "phmax": 7.0,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 100.0,
  "altitudemax": 5000.0,
  "image": null,
  "season": "SPRING",
  "harvest": 3.0,
  "is_terrace": "YEs",
  "link": "https://en.wikipedia.org/wiki/Cucumber"
},
{
  "id": 17,
  "local_name": "Garlic",
  "scientific_name": "Allium Sativum",
  "description": "Allium sativum is a perennial flowering plant growing from a bulb. It has a tall, erect flowering stem that grows up to 1 m (3 ft). The leaf blade is flat, linear, solid, and approximately 1.25–2.5 cm (0.5–1.0 in) wide, with an acute apex.",
  "category": "VEGETABLE",
  "tempmin": 0.0,
  "tempmax": 10.0,
  "rainmin": null,
  "rainmax": null,
  "phmin": 5.5,
  "phmax": 7.5,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 1200.0,
  "altitudemax": 2000.0,
  "image": null,
  "season": "SPRING",
  "harvest": 8.0,
  "is_terrace": "YEs",
  "link": "https://en.wikipedia.org/wiki/Garlic"
},
{
  "id": 18,
  "local_name": "Turnip",
  "scientific_name": "Brassica rapa subsp. rapa",
  "description": "The turnip is a root vegetable commonly grown in temperate climates worldwide for its white, fleshy taproot. Small, tender varieties are grown for human consumption, while larger varieties are grown as feed for livestock.",
  "category": "VEGETABLE",
  "tempmin": 40.0,
  "tempmax": 75.0,
  "rainmin": null,
  "rainmax": null,
  "phmin": 5.5,
  "phmax": 7.0,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 1000.0,
  "altitudemax": 1500.0,
  "image": null,
  "season": "WINTER",
  "harvest": 2.0,
  "is_terrace": "YEs",
  "link": "https://en.wikipedia.org/wiki/Turnip"
},
{
  "id": 19,
  "local_name": "Radish",
  "scientific_name": "Raphanus Sativus",
  "description": "Radishes are grown and consumed throughout the world, being mostly eaten raw as a crunchy salad vegetable with a pungent flavor. They germinate quickly and grow rapidly.",
  "category": "VEGETABLE",
  "tempmin": 40.0,
  "tempmax": 70.0,
  "rainmin": null,
  "rainmax": null,
  "phmin": 6.0,
  "phmax": 7.0,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 100.0,
  "altitudemax": 3000.0,
  "image": null,
  "season": "WINTER",
  "harvest": 4.0,
  "is_terrace": "YEs",
  "link": "https://en.wikipedia.org/wiki/Radish"
},
{
  "id": 20,
  "local_name": "Potato",
  "scientific_name": "Solanum tuberosum",
  "description": "The potato is a starchy tuber of the plant Solanum tuberosum and is a root vegetable native to the Americas. The plant is a perennial in the nightshade family Solanaceae.",
  "category": "VEGETABLE",
  "tempmin": 16.0,
  "tempmax": 19.0,
  "rainmin": null,
  "rainmax": null,
  "phmin": 5.5,
  "phmax": 7.5,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 1600.0,
  "altitudemax": 3200.0,
  "image": null,
  "season": "WINTER",
  "harvest": 4.0,
  "is_terrace": "YEs",
  "link": "https://en.wikipedia.org/wiki/Potato"
},
{
  "id": 21,
  "local_name": "Mango",
  "scientific_name": "Mangifera",
  "description": "A mango is an edible stone fruit produced by the tropical tree Mangifera indica which is believed to have originated from the region between northwestern Myanmar, Bangladesh, and northeastern India.",
  "category": "FRUIT",
  "tempmin": 27.0,
  "tempmax": 36.0,
  "rainmin": null,
  "rainmax": null,
  "phmin": 5.5,
  "phmax": 7.5,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 100.0,
  "altitudemax": 1500.0,
  "image": null,
  "season": "SUMMER",
  "harvest": 80.0,
  "is_terrace": "NO",
  "link": "https://en.wikipedia.org/wiki/Mango"
},
{
  "id": 22,
  "local_name": "Apple",
  "scientific_name": "Malus",
  "description": "An apple is an edible fruit produced by an apple tree (Malus domestica). Apple trees are cultivated worldwide and are the most widely grown species in the genus Malus.",
  "category": "FRUIT",
  "tempmin": 21.0,
  "tempmax": 24.0,
  "rainmin": null,
  "rainmax": null,
  "phmin": 5.8,
  "phmax": 7.0,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 1500.0,
  "altitudemax": 2700.0,
  "image": null,
  "season": "WINTER",
  "harvest": 36.0,
  "is_terrace": "NO",
  "link": "https://en.wikipedia.org/wiki/Apple"
},
{
  "id": 23,
  "local_name": "Onion",
  "scientific_name": "Allium cepa",
  "description": "The onion is a vegetable that is the most widely cultivated species of the genus Allium. The shallot is a botanical variety of the onion which was classified as a separate species until 2010.  Its close relatives include garlic, scallion, leek, and chive.",
  "category": "VEGETABLE",
  "tempmin": 12.0,
  "tempmax": 23.0,
  "rainmin": null,
  "rainmax": null,
  "phmin": 6.0,
  "phmax": 7.0,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 100.0,
  "altitudemax": 1900.0,
  "image": null,
  "season": "AUTUMN",
  "harvest": 4.0,
  "is_terrace": "YEs",
  "link": "https://en.wikipedia.org/wiki/Onion"
},
{
  "id": 24,
  "local_name": "Pumpkin",
  "scientific_name": "Cucurbita",
  "description": "A pumpkin is a cultivar of winter squash that is round with smooth, slightly ribbed skin, and is most often deep yellow to orange in coloration.",
  "category": "VEGETABLE",
  "tempmin": 23.0,
  "tempmax": 29.0,
  "rainmin": null,
  "rainmax": null,
  "phmin": 6.0,
  "phmax": 6.5,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 750.0,
  "altitudemax": 2500.0,
  "image": null,
  "season": "AUTUMN",
  "harvest": 4.0,
  "is_terrace": "YEs",
  "link": "https://en.wikipedia.org/wiki/Pumpkin"
},
{
  "id": 25,
  "local_name": "Walnut",
  "scientific_name": "Juglans",
  "description": "A walnut is the edible seed of a drupe of any tree of the genus Juglans (family Juglandaceae).Although culinarily considered a \"nut\" and used as such, it is not a true botanical nut. After full ripening, the shell is discarded and the kernel is eaten.",
  "category": "FRUIT",
  "tempmin": -6.0,
  "tempmax": 40.0,
  "rainmin": null,
  "rainmax": null,
  "phmin": 5.0,
  "phmax": 8.0,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 1000.0,
  "altitudemax": 4000.0,
  "image": null,
  "season": "SPRING",
  "harvest": 84.0,
  "is_terrace": "NO",
  "link": "https://en.wikipedia.org/wiki/Walnut"
},
{
  "id": 26,
  "local_name": "Clove",
  "scientific_name": "Syzygium aromaticum",
  "description": "Cloves are the aromatic flower buds of a tree in the family Myrtaceae, Syzygium aromaticum. They are commonly used as a spice, flavoring or fragrance in consumer products, such as toothpaste, soaps, or cosmetics.",
  "category": "Cash Crop",
  "tempmin": 25.0,
  "tempmax": 35.0,
  "rainmin": null,
  "rainmax": null,
  "phmin": 6.5,
  "phmax": 8.0,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 100.0,
  "altitudemax": 1500.0,
  "image": null,
  "season": "SUMMER",
  "harvest": 84.0,
  "is_terrace": "NO",
  "link": "https://en.wikipedia.org/wiki/Clove"
},
{
  "id": 27,
  "local_name": "Cardamom",
  "scientific_name": "Elettaria Cardamomum",
  "description": "Cardamom is a spice made from the seeds of several plants in the genera Elettaria and Amomum in the family Zingiberaceae. Both genera are native to the Indian subcontinent and Indonesia.",
  "category": "Cash Crop",
  "tempmin": 10.0,
  "tempmax": 35.0,
  "rainmin": 150.0,
  "rainmax": 400.0,
  "phmin": 5.5,
  "phmax": 6.5,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 1200.0,
  "altitudemax": 2000.0,
  "image": null,
  "season": "SPRING",
  "harvest": 4.0,
  "is_terrace": "NO",
  "link": "https://en.wikipedia.org/wiki/Cardamom"
},
{
  "id": 28,
  "local_name": "Turmeric",
  "scientific_name": "Curcuma",
  "description": "Turmeric is a flowering plant, Curcuma longa, of the ginger family, Zingiberaceae, the rhizomes of which are used in cooking. The plant is a perennial, rhizomatous, herbaceous plant native to the Indian subcontinent and Southeast Asia.",
  "category": "Cash Crop",
  "tempmin": 20.0,
  "tempmax": 30.0,
  "rainmin": 150.0,
  "rainmax": 250.0,
  "phmin": 4.5,
  "phmax": 7.5,
  "organicmin": null,
  "organicmax": null,
  "altitudemin": 100.0,
  "altitudemax": 1500.0,
  "image": null,
  "season": "AUTUMN",
  "harvest": 8.0,
  "is_terrace": "YEs",
  "link": "https://en.wikipedia.org/wiki/Turmeric"
},
{
  "id": 29,
  "local_name": "test",
  "scientific_name": "test",
  "description": "test",
  "category": "FRUIT",
  "tempmin": 50.0,
  "tempmax": 55.0,
  "rainmin": 50.0,
  "rainmax": 55.0,
  "phmin": 50.0,
  "phmax": 55.0,
  "organicmin": 50.0,
  "organicmax": 55.0,
  "altitudemin": 50.0,
  "altitudemax": 55.0,
  "image": null,
  "season": "WINTER",
  "harvest": 1.0,
  "is_terrace": "YEs",
  "link": "https://anukul.com.np"
}
]